on:
  pull_request:

name: Validate Pull Request

jobs:
  validate_smart_contracts:
    name: Validate Smart Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        # https://github.com/marketplace/actions/foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run tests
        run: forge test -vvv

      - name: Run snapshot
        run: forge snapshot
