on:
  pull_request:
  workflow_dispatch:

name: Validate Pull Request

jobs:
  validate_smart_contracts:
    name: Validate Smart Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        # https://github.com/marketplace/actions/foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1

      - name: Set GitHub author identity
        run: git config --global user.email vince.grondin@gmail.com git config --global user.name "Roch Grondin"

      - name: Install libraries
        run: forge install OpenZeppelin/openzeppelin-contracts

      - name: Run tests
        run: forge test -vvv

      - name: Run snapshot
        run: forge snapshot
